export const CONSTANTES = {
  NM_TP_RUBRICA_RECEITA: 'RECEITA',
  NM_TP_RUBRICA_DESPESA: 'DESPESA',
  NM_TP_LANCAMENTO_CREDITO: 'CREDITO',
  NM_TP_LANCAMENTO_DEBITO: 'DEBITO',
  NM_VL_BALANCO_ANUAL: '1',
  NM_VL_BALANCO_MENSAL: '2',

  
}

export const MAP_TP_RUBRICA_TP_LANCAMENTO: Map<string, string> =new Map();
MAP_TP_RUBRICA_TP_LANCAMENTO.set(CONSTANTES.NM_TP_RUBRICA_RECEITA,
  CONSTANTES.NM_TP_LANCAMENTO_CREDITO);
MAP_TP_RUBRICA_TP_LANCAMENTO.set(CONSTANTES.NM_TP_RUBRICA_DESPESA,
  CONSTANTES.NM_TP_LANCAMENTO_DEBITO);